stages:
  ingest:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw/data.csv
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/raw/data.csv